# Generated by Django 4.2.13 on 2024-07-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата за текущий месяц')),
                ('paid_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выплаченная зарплата')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонусы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
